### ISSUE TITLE
Input file name parameter issues when converting images

### ISSUE THREAD

**Issue by HongxuChen** [jcupitt/libvips#1040]
This was found quite accidentally when fuzzing the `vips` driver (#1039 ) .

- Determine the file name incorrectly
```
$ vips im_copy /tmp/tes:i /tmp/test.pbm
VipsFormat: file "/tmp/tes" not found
memory: high-water mark 0 bytes
error buffer: VipsFormat: file "/tmp/tes" not found
```

And

```
$ vips im_copy /tmp/test:i /tmp/test.pbm
AddressSanitizer:DEADLYSIGNAL
=================================================================
==5165==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004269d3 bp 0x7ffdae078420 sp 0x7ffdae0783d0 T0)
==5165==The signal is caused by a READ memory access.
==5165==Hint: address points to the zero page.
    #0 0x4269d2 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) (/home/hongxu/FOT/libvips/install/bin/vips+0x4269d2)
    #1 0x4db18a in __interceptor_free.localalias.0 (/home/hongxu/FOT/libvips/install/bin/vips+0x4db18a)
    #2 0x7ffbd3bc6ef4 in buffer_free /home/hongxu/FOT/libvips/libvips/foreign/radiance.c:655:2
    #3 0x7ffbd3bc6d7a in read_destroy /home/hongxu/FOT/libvips/libvips/foreign/radiance.c:956:2
    #4 0x7ffbcfd80f6c in g_closure_invoke (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0xff6c)
    #5 0x7ffbcfd93d3d  (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x22d3d)
    #6 0x7ffbcfd9c3f4 in g_signal_emit_valist (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x2b3f4)
    #7 0x7ffbcfd9ce0e in g_signal_emit (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x2be0e)
    #8 0x7ffbd3d15676 in vips_object_close /home/hongxu/FOT/libvips/libvips/iofuncs/object.c:291:3
    #9 0x7ffbd3d14943 in vips_object_dispose /home/hongxu/FOT/libvips/libvips/iofuncs/object.c:1022:2
    #10 0x7ffbd3d257fa in vips_image_dispose /home/hongxu/FOT/libvips/libvips/iofuncs/image.c:540:2
    #11 0x7ffbcfd85e02 in g_object_unref (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0+0x14e02)
    #12 0x7ffbd3d13ec7 in vips_object_unref_outputs_sub /home/hongxu/FOT/libvips/libvips/iofuncs/object.c:3070:3
    #13 0x7ffbd3d02c86 in vips_argument_map /home/hongxu/FOT/libvips/libvips/iofuncs/object.c:606:17
    #14 0x7ffbd3d13ab2 in vips_object_unref_outputs /home/hongxu/FOT/libvips/libvips/iofuncs/object.c:3092:9
    #15 0x7ffbd3d56b01 in vips_call_by_name /home/hongxu/FOT/libvips/libvips/iofuncs/operation.c:925:3
    #16 0x7ffbd3d56e3d in vips_call_split /home/hongxu/FOT/libvips/libvips/iofuncs/operation.c:1024:11
    #17 0x7ffbd3bcd010 in vips_radload /home/hongxu/FOT/libvips/libvips/foreign/radload.c:182:11
    #18 0x7ffbd3b9d3a0 in im_rad2vips /home/hongxu/FOT/libvips/libvips/deprecated/radiance.c:47:6
    #19 0x7ffbd3aee2c9 in vips_image_open_lazy /home/hongxu/FOT/libvips/libvips/deprecated/lazy.c:232:7
    #20 0x7ffbd3aede2b in vips__deprecated_open_read /home/hongxu/FOT/libvips/libvips/deprecated/lazy.c:301:7
    #21 0x7ffbd3b6c104 in input_image_init /home/hongxu/FOT/libvips/libvips/deprecated/dispatch_types.c:95:18
    #22 0x7ffbd3b71038 in build_args /home/hongxu/FOT/libvips/libvips/deprecated/package.c:1008:22
    #23 0x7ffbd3b6f4dd in dispatch_function /home/hongxu/FOT/libvips/libvips/deprecated/package.c:1118:6
    #24 0x7ffbd3b6f414 in im_run_command /home/hongxu/FOT/libvips/libvips/deprecated/package.c:1186:6
    #25 0x5148a5 in main /home/hongxu/FOT/libvips/tools/vips.c:1246:7
    #26 0x7ffbcbf09b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #27 0x41b4c9 in _start (/home/hongxu/FOT/libvips/install/bin/vips+0x41b4c9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/hongxu/FOT/libvips/install/bin/vips+0x4269d2) in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType)
==5165==ABORTING
[1]    5165 abort      /home/hongxu/FOT/libvips/install/bin/vips im_copy /tmp/test:i /tmp/test.pbm
```

- Treating special symbols wrongly (essentially it may be because that it will be treated as the empty file name)
``` vips im_copy '' /tmp/test.pbm
=================================================================
==4606==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffc8e4cb65f at pc 0x7f6b2ba0c0e5 bp 0x7ffc8e4cb530 sp 0x7ffc8e4cb528
READ of size 1 at 0x7ffc8e4cb65f thread T0
    #0 0x7f6b2ba0c0e4 in im_filename_split /home/hongxu/FOT/libvips/libvips/deprecated/vips7compat.c:118:6
    #1 0x7f6b2ba59fdd in vips_format_for_file /home/hongxu/FOT/libvips/libvips/deprecated/format.c:348:2
    #2 0x7f6b2b9b9dba in vips__deprecated_open_read /home/hongxu/FOT/libvips/libvips/deprecated/lazy.c:285:17
    #3 0x7f6b2ba38104 in input_image_init /home/hongxu/FOT/libvips/libvips/deprecated/dispatch_types.c:95:18
    #4 0x7f6b2ba3d038 in build_args /home/hongxu/FOT/libvips/libvips/deprecated/package.c:1008:22
    #5 0x7f6b2ba3b4dd in dispatch_function /home/hongxu/FOT/libvips/libvips/deprecated/package.c:1118:6
    #6 0x7f6b2ba3b414 in im_run_command /home/hongxu/FOT/libvips/libvips/deprecated/package.c:1186:6
    #7 0x5148a5 in main /home/hongxu/FOT/libvips/tools/vips.c:1246:7
    #8 0x7f6b23dd5b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #9 0x41b4c9 in _start (/home/hongxu/FOT/libvips/install/bin/vips+0x41b4c9)

Address 0x7ffc8e4cb65f is located in stack of thread T0 at offset 31 in frame
    #0 0x7f6b2ba59e6f in vips_format_for_file /home/hongxu/FOT/libvips/libvips/deprecated/format.c:340

  This frame has 2 object(s):
    [32, 4128) 'name' (line 341) <== Memory access at offset 31 underflows this variable
    [4256, 8352) 'options' (line 342)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow /home/hongxu/FOT/libvips/libvips/deprecated/vips7compat.c:118:6 in im_filename_split
Shadow bytes around the buggy address:
  0x100011c91670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c91680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c91690: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c916a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c916b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100011c916c0: 00 00 00 00 00 00 00 00 f1 f1 f1[f1]00 00 00 00
  0x100011c916d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c916e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c916f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c91700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011c91710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==4606==ABORTING
```

**Comment by HongxuChen** [comment]
`vips copy` does not have this issue.

**Comment by jcupitt** [comment]
Hi again, I'm not able to reproduce this. I see:

```
$ valgrind vips im_copy /tmp/test:i /tmp/test.pbm
==22961== Memcheck, a memory error detector
==22961== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22961== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22961== Command: vips im_copy /tmp/test:i /tmp/test.pbm
==22961== 
VipsFormat: file "/tmp/test" not found
==22961== 
==22961== HEAP SUMMARY:
==22961==     in use at exit: 203,654 bytes in 1,819 blocks
==22961==   total heap usage: 3,948 allocs, 2,129 frees, 610,907 bytes allocated
==22961== 
==22961== LEAK SUMMARY:
==22961==    definitely lost: 0 bytes in 0 blocks
==22961==    indirectly lost: 0 bytes in 0 blocks
==22961==      possibly lost: 0 bytes in 0 blocks
==22961==    still reachable: 63,172 bytes in 146 blocks
==22961==                       of which reachable via heuristic:
==22961==                         newarray           : 1,536 bytes in 16 blocks
==22961==         suppressed: 140,482 bytes in 1,673 blocks
==22961== Rerun with --leak-check=full to see details of leaked memory
==22961== 
==22961== For counts of detected and suppressed errors, rerun with: -v
==22961== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Is there something else I need to do to trigger this?

**Comment by HongxuChen** [comment]
Not sure about it, let me check this tomorrow.

**Comment by HongxuChen** [comment]
When I built with default compilation options it it caused segment fault.

Configuration results (I used `./autogen.sh --prefix=$PWD/install --exec-prefix=$PWD/install`) and messages when running with valgrind are [here](https://gist.github.com/HongxuChen/005c7cc7c5887ec96fecc05c47a35e07).

**Comment by jcupitt** [comment]
Huh strange, still not seeing it here.

I did notice a small problem from your stack trace, it might be fixed now.

**Comment by HongxuChen** [comment]
Yes, the behavior is now the same as `/tmp/tes:i`.

**Comment by jcupitt** [comment]
So fixed? That's great, I'll close.

**Comment by HongxuChen** [comment]
@jcupitt I think that issue is fixed; the other two are not (`tes:i` is recognized as `tes`; empty file name crashes).

**Comment by jcupitt** [comment]
Ah, got it, perhaps.

**Comment by jcupitt** [comment]
I think this is fixed now, I'll close. Thanks again!
