### ISSUE TITLE
Invalid pointer

### ISSUE THREAD

**Issue by binarykitchen** [jcupitt/libvips#419]
Getting an invalid pointer somewhere deep in the sharp code. This with your latest version compiled from master:

```
$ vips --vips-version                                                                                    master 
libvips 8.3.0-Thu Apr  7 19:27:36 NZST 2016
```

```
*** Error in `/usr/bin/node': free(): invalid pointer: 0x0000000001d89690 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe8b74700 (LWP 6722)]
0x00007ffff6b79267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6b79267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6b7aeca in __GI_abort () at abort.c:89
#2  0x00007ffff6bbcbf3 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff6cd5168 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6bc417a in malloc_printerr (ptr=<optimised out>, str=0x7ffff6cd12ba "free(): invalid pointer", 
    action=<optimised out>) at malloc.c:4965
#4  free_check (mem=<optimised out>, caller=<optimised out>) at hooks.c:298
#5  0x00007ffff6bc88e7 in __GI___libc_free (mem=<optimised out>) at malloc.c:2924
#6  0x00007ffff46fbb5d in vips::VImage::call_option_string (
    operation_name=operation_name@entry=0x7ffff42c8b19 "VipsForeignLoadJpegFile", 
    option_string=option_string@entry=0x7fffe8b727d0 "", options=0x1d89690) at VImage.cpp:499
#7  0x00007ffff47107d8 in vips::VImage::new_from_file (name=<optimised out>, options=0x1d89690) at VImage.cpp:532
#8  0x00007ffff4930a9e in PipelineWorker::Execute() ()
   from /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/build/Release/sharp.node
#9  0x0000000000fd2081 in ?? ()
#10 0x0000000000fe11f8 in ?? ()
#11 0x00007ffff6f156aa in start_thread (arg=0x7fffe8b74700) at pthread_create.c:333
#12 0x00007ffff6c4ae9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Comment by lovell** [comment]
This has been cross-posted - see https://github.com/lovell/sharp/issues/401 - please can we continue this discussion within sharp as that issue provides a more complete background.

**Comment by binarykitchen** [comment]
ok, let's discuss over there https://github.com/lovell/sharp/issues/401
