### ISSUE TITLE
Failed test

### ISSUE THREAD

**Issue by awissu** [jcupitt/libvips#551]
```
[  279s] Traceback (most recent call last):
[  279s]   File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
[  279s]     "__main__", fname, loader, pkg_name)
[  279s]   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
[  279s]     exec code in run_globals
[  279s]   File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
[  279s]     main(module=None)
[  279s]   File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
[  279s]     self.parseArgs(argv)
[  279s]   File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
[  279s]     self.createTests()
[  279s]   File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
[  279s]     self.module)
[  279s]   File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
[  279s]     suites = [self.loadTestsFromName(name, module) for name in names]
[  279s]   File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
[  279s]     module = __import__('.'.join(parts_copy))
[  279s] ImportError: No module named test_all
[  279s] FAIL test_python.sh (exit status: 1)
```
See: https://build.opensuse.org/package/live_build_log/home:awissu:branches:graphics/vips/openSUSE_Tumbleweed/x86_64

**Comment by jcupitt** [comment]
Sorry, no idea, other than that I guess there's some kind of packaging problem.

**Comment by awissu** [comment]
Problem temporarily solved.
Use --disable-pyvips8

**Comment by jcupitt** [comment]
Good enough for now I guess. I'll close.
