### ISSUE TITLE
libvips glib core dump issue

### ISSUE THREAD

**Issue by juyunsang** [jcupitt/libvips#573]
Good morning
When I use libvips, I have a problem with certain image, and I can see core dump as below.
```
53	../sysdeps/unix/sysv/linux/x86_64/sigaction.c: No such file or directory.
(gdb) where
#0  0x00007f19b1f5dcc9 in __GI___libc_sigaction (sig=103509, act=0x19488, oact=0x6) at ../sysdeps/unix/sysv/linux/x86_64/sigaction.c:53
#1  0x00007f1900000030 in ?? ()
#2  0x00007f198c018d30 in ?? ()
#3  0x00007f198c000020 in ?? ()
#4  0x0000000000000053 in ?? ()
#5  0x0000000000000053 in ?? ()
#6  0x00007f19b298183a in ?? () from /usr/lib/libvips.so.42
#7  0x00007f198c018d30 in ?? ()
#8  0x00007f19b014c3a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x0000000000000053 in ?? ()
#10 0x00007f19b298183a in ?? () from /usr/lib/libvips.so.42
#11 0x00007f19b2981831 in ?? () from /usr/lib/libvips.so.42
#12 0x00007f19a734a700 in ?? ()
#13 0x00007f19afeb2165 in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f19afeb21fa in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

The vips stdout error log is 	
```
VIPS:ERROR:region.c:887:vips_region_fill: assertion failed: (reg->im->generate_fn)
	, Throwable Error Msg is Process exited with an error: 134 (Exit value: 134)
```
Glib-dev2.0 Installation is complete.
When I googling, I get an error like this with the gcc version,
Is there a gcc version I need to compile libvips?
I am currently compiling with gcc 4.8 version.

**Comment by jcupitt** [comment]
Hi again, did you make any progress on this issue?

**Comment by juyunsang** [comment]
I kept following the problem,
The problem appears to be only in corrupted image.
We are still watching.

**Comment by jcupitt** [comment]
Could you send me a sample corrupt image?

**Comment by juyunsang** [comment]
The corresponding error is not currently occurring.
Thank you for answer.
