### ISSUE TITLE
Segmentation fault with a 1x1 GIF image

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/libvips#773]
When loading a 1x1 GIF image through libvips it segfaults. 

Test image: https://t0.nl/1x1.gif

Reproducible with:
```bash
vips copy 1x1.gif x.jpg
```

GDB backtrace:
```
#0  0x00006e0bc3f1be46 in vips_foreign_load_gif_page (out=0x46d3190 [VipsImage], gif=0x46d2050 [VipsForeignLoadGifFile]) at gifload.c:420
#1  0x00006e0bc3f1be46 in vips_foreign_load_gif_page (gif=gif@entry=0x46d2050 [VipsForeignLoadGifFile], out=out@entry=0x46d3190 [VipsImage]) at gifload.c:519
#2  0x00006e0bc3f1c165 in vips_foreign_load_gif_load (out=0x46d2fd0, gif=0x46d2050 [VipsForeignLoadGifFile]) at gifload.c:665
#3  0x00006e0bc3f1c165 in vips_foreign_load_gif_load (load=0x46d2050 [VipsForeignLoadGifFile]) at gifload.c:764
#4  0x00006e0bc3f2c7d7 in vips_foreign_load_build (object=0x46d2050 [VipsForeignLoadGifFile]) at foreign.c:925
#5  0x00006e0bc3f6bfa8 in vips_object_build (object=0x46d2050 [VipsForeignLoadGifFile]) at object.c:342
#6  0x00006e0bc3f77778 in vips_cache_operation_buildp (operation=operation@entry=0x7be2b7967170) at cache.c:860
#7  0x00006e0bc3f7cdb1 in vips_call_required_optional (operation=operation@entry=0x7be2b7967170, required=required@entry=0x7be2b79671a0, optional=optional@entry=0x7be2b7967288) at operation.c:880
#8  0x00006e0bc3f7d706 in vips_call_by_name (operation_name=<optimized out>, option_string=0x7be2b79682a0 "", required=required@entry=0x7be2b79671a0, optional=optional@entry=0x7be2b7967288) at operation.c:920
#9  0x00006e0bc3f7dc42 in vips_call_split_option_string (operation_name=<optimized out>, option_string=option_string@entry=0x7be2b79682a0 "", optional=optional@entry=0x7be2b7967288) at operation.c:1039
#10 0x00006e0bc3f71fcc in vips_image_new_from_file (name=name@entry=0x7be2b7969895 "1x1.gif") at image.c:1916
#11 0x00006e0bc3f6db7e in vips_object_set_argument_from_string (object=object@entry=0x46d0020 [VipsCopy], name=0x45ffc53 "in", value=0x7be2b7969895 "1x1.gif") at object.c:1870
#12 0x00006e0bc3f7c79e in vips_call_argv_input (object=0x46d0020 [VipsCopy], pspec=0x4677650 [GParamObject], argument_class=0x4679260, argument_instance=<optimized out>, a=0x7be2b79694d0, b=<optimized out>) at operation.c:1277
#13 0x00006e0bc3f6bdea in vips_argument_map (object=0x46d0020 [VipsCopy], fn=fn@entry=0x6e0bc3f7c700 <vips_call_argv_input>, a=a@entry=0x7be2b79694d0, b=b@entry=0x0) at object.c:581
#14 0x00006e0bc3f7dcf9 in vips_call_argv (operation=operation@entry=0x46d0020 [VipsCopy], argc=2, argv=<optimized out>) at operation.c:1361
#15 0x0000000000402331 in main (argc=3, argv=0x7be2b7969648) at vips.c:1268
```

GDB backtrace (full):
```
#0  0x00006e0bc3f1be46 in vips_foreign_load_gif_page (out=0x46d3190 [VipsImage], gif=0x46d2050 [VipsForeignLoadGifFile]) at gifload.c:420
        i = 0
        class = 0x469cd10
        file = 0x46d44e0
        map = 0x0
        extension = 0x0
        ext_code = 249
        record = IMAGE_DESC_RECORD_TYPE
        n_pages = 0
#1  0x00006e0bc3f1be46 in vips_foreign_load_gif_page (gif=gif@entry=0x46d2050 [VipsForeignLoadGifFile], out=out@entry=0x46d3190 [VipsImage]) at gifload.c:519
        extension = 0x0
        ext_code = 249
        record = IMAGE_DESC_RECORD_TYPE
        n_pages = 0
#2  0x00006e0bc3f1c165 in vips_foreign_load_gif_load (out=0x46d2fd0, gif=0x46d2050 [VipsForeignLoadGifFile]) at gifload.c:665
        frames = 0x0
        frame = 0x46d3190 [VipsImage]
        i = <optimized out>
        class = 0x469cd10
        previous = 0x0
        t = <optimized out>
        n_frames = <optimized out>
        gif = 0x46d2050 [VipsForeignLoadGifFile]
        t = 0x46d2fd0
        im = <optimized out>
#3  0x00006e0bc3f1c165 in vips_foreign_load_gif_load (load=0x46d2050 [VipsForeignLoadGifFile]) at gifload.c:764
        gif = 0x46d2050 [VipsForeignLoadGifFile]
        t = 0x46d2fd0
        im = <optimized out>
#4  0x00006e0bc3f2c7d7 in vips_foreign_load_build (object=0x46d2050 [VipsForeignLoadGifFile]) at foreign.c:925
        class = 0x469cd10
        load = 0x46d2050 [VipsForeignLoadGifFile]
        fclass = 0x469cd10
        flags = <optimized out>
#5  0x00006e0bc3f6bfa8 in vips_object_build (object=0x46d2050 [VipsForeignLoadGifFile]) at object.c:342
        object_class = <optimized out>
        iomask = (VIPS_ARGUMENT_INPUT | VIPS_ARGUMENT_OUTPUT)
        result = <optimized out>
#6  0x00006e0bc3f77778 in vips_cache_operation_buildp (operation=operation@entry=0x7be2b7967170) at cache.c:860
        hit = 0x0
#7  0x00006e0bc3f7cdb1 in vips_call_required_optional (operation=operation@entry=0x7be2b7967170, required=required@entry=0x7be2b79671a0, optional=optional@entry=0x7be2b7967288) at operation.c:880
        result = 0
        a = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7be2b7967280, reg_save_area = 0x7be2b79671c0}}
        b = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7be2b7969380, reg_save_area = 0x7be2b79692b0}}
#8  0x00006e0bc3f7d706 in vips_call_by_name (operation_name=<optimized out>, option_string=0x7be2b79682a0 "", required=required@entry=0x7be2b79671a0, optional=optional@entry=0x7be2b7967288) at operation.c:920
        operation = 0x46d2050 [VipsForeignLoadGifFile]
        result = <optimized out>
#9  0x00006e0bc3f7dc42 in vips_call_split_option_string (operation_name=<optimized out>, option_string=option_string@entry=0x7be2b79682a0 "", optional=optional@entry=0x7be2b7967288) at operation.c:1039
        result = <optimized out>
        required = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7be2b7967280, reg_save_area = 0x7be2b79671c0}}
#10 0x00006e0bc3f71fcc in vips_image_new_from_file (name=name@entry=0x7be2b7969895 "1x1.gif") at image.c:1916
        filename = "1x1.gif\000X\316G\275\vn\000\000\340\336a\004\000\000\000\000ǳ@\304\vn\000\000\000\000\000\000\000\000\000\377\000\000\000\000\377\000\000\000e_table\000\237`V\275\vn\000\000\260\217\002\000\000\000\000\000\270\067\203\275\vn\000\000\340?\203\275\vn\000\000Y\243O\275\vn\000\000\000\000\000\000\000\000\000\000\037\034O\275\vn\000\000UTF-8\000LAP\340a\004\000\000\000\000`7\203\275\vn\000\000\260\217\002", '\000' <repeats 13 times>, "\220`b\004\000\000\000\000p\017\002\000\000\000\000\000\332\064O\275\vn\000\000(/b\004\000\000\000\000:/b\004\000\000\000\000\n\000\000\000\000\000\000\000\366"...
        option_string = "\000\000\000\000\vn\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\300Qa\304\vn\000\000\000\000\000\000 ", '\000' <repeats 19 times>, "x\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000\230ya\304\vn\000\000\200Z?\304\vn\000\000\a\000\000\000\000\000\000\000\070T?\304\vn\000\000\320oa\304\vn\000\000P\204\226\267\342{\000\000\317\017@\304\vn\000\000\001\000\000\000\342{", '\000' <repeats 14 times>, "\342{\000\000\220\211_\304\vn\000\000\300\203\226\267\342{\000\000ȃ\226\267\342{\000\000؃\226\267\342{\000\000\000\000\000\000\000\000\000\000\070\204\226\267\342{", '\000' <repeats 18 times>...
        operation_name = <optimized out>
        ap = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x7be2b7969380, reg_save_area = 0x7be2b79692b0}}
        out = 0x461dee0
        result = <optimized out>
#11 0x00006e0bc3f6db7e in vips_object_set_argument_from_string (object=object@entry=0x46d0020 [VipsCopy], name=0x45ffc53 "in", value=0x7be2b7969895 "1x1.gif") at object.c:1870
```

Looks like there is something wrong here: https://github.com/jcupitt/libvips/blob/bea3d0cc58170be3db8bf000ce4b28f48d13e5a0/libvips/foreign/gifload.c#L420

Tested with libvips 8.6.0-alpha5 and giflib 4.1.6.

**Comment by jcupitt** [comment]
I agree, I'm seeing the crash here too. I'll investigate.

**Comment by jcupitt** [comment]
OK, fixed in master. Thanks for the great report!
