### ISSUE TITLE
pyvips save to multipage tiff

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#789]
Notice that there is multipage tiff write support in vips
https://github.com/jcupitt/libvips/issues/513

Try to save multiple images to one tiff file using tiffsave_multi
but get error
```
pyvips.error.Error: no such operation tiffsave_multi
  VipsOperation: class "tiffsave_multi" not found
```

**Comment by jindili** [comment]
sorry not read carefully enough,

tiffsave could look for a tall, thin image with page-height set and save the image as a multi-page tiff.

**Comment by jcupitt** [comment]
You set the page height as metadata on the image. For example:

```python
b = a.join(a, 'vertical')
a.set('page-height', a.height)
b.write_to_file('x.tif')
```

Will make a two-page tiff.

**Comment by jindili** [comment]
I run this simple python code:
```
a1 = pyvips.Image.new_from_file("shape1.jpg")
a2 = pyvips.Image.new_from_file("shape2.jpg")

b = a1.join(a2, 'vertical')
b.set('page-height', a1.height)
b.write_to_file('x.tif')
```

get error:

```
C:\Python27_64\python.exe D:/Dev/autoPrint/testMultiTiff.py
Traceback (most recent call last):
  File "D:/Dev/autoPrint/testMultiTiff.py", line 7, in <module>
    b.set('page-height', a1.height)
  File "C:\Python27_64\lib\site-packages\pyvips\vimage.py", line 741, in set
    self.set_type(gtype, name, value)
  File "C:\Python27_64\lib\site-packages\pyvips\vimage.py", line 719, in set_type
    gv.set(value)
  File "C:\Python27_64\lib\site-packages\pyvips\gvalue.py", line 242, in set
    format(type_name(gtype), type_name(fundamental)))
  File "C:\Python27_64\lib\site-packages\pyvips\base.py", line 85, in type_name
    return _to_string(ffi.string(gobject_lib.g_type_name(gtype)))
  File "C:\Python27_64\lib\site-packages\cffi\api.py", line 301, in string
    return self._backend.string(cdata, maxlen)
RuntimeError: cannot use string() on <cdata 'char *' NULL>

(testMultiTiff.py:26600): GLib-GObject-WARNING **: gtype.c:4265: type id '0' is invalid

(testMultiTiff.py:26600): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced

(testMultiTiff.py:26600): GLib-GObject-WARNING **: gvalue.c:188: cannot initialize GValue with type '(NULL)', this type has no GTypeValueTable implementation

Process finished with exit code 1
```

**Comment by jcupitt** [comment]
Sorry, I should have tested the code.

Because the `page-height` property does not exist, you have to create it. The error message should be better.

Try:

```python
page = pyvips.Image.new_from_file(sys.argv[1])
pages = page.join(page, 'vertical')
pages.set_type(pyvips.GValue.gint_type, 'page-height', page.height)
pages.write_to_file(sys.argv[2])
```
